#+title: 我的i3wm

* 从 kde 切换到 i3 的动机
我一直使用 kde，从 kde3 到现在的 plasma，期间也尝试过别的 wm，但是都只是简单安装和试用，没有深入体会过不同类型 wm 的特点。直到最近看到一片文章 [[https://sspai.com/post/52548][跨平台生产力指南--2018年我对于数字生产力的思考]] , 这篇文章分别从道，术，器三个层次讲述了工具对生产力的影响。于是在文章的指引下，将我的桌面切换到了 i3wm。

* 我的工具集：
| i3wm          | 平铺类窗口管理  |
| polybar       | 系统工具/状态栏 |
| jgmenu        | 系统 app 菜单   |
| rofi          | 快速启动        |
| tdop          | 快速访问工具    |
| tmux          | 终端管理        |
| emacs         | 文本编辑        |
| krusader      | 文件浏览        |
| konsole       | 终端            |
| dunst         | 通知管理        |
| feh           | 壁纸            |
| nmcli         | 网络配置        |
| pulsemixer    | 音量控制        |
| xrandr,arandr | 屏幕控制        |
| dde-calendar  | 日历            |

具体配置参考：https://github.com/renshuo/shellScript.git 的 config/i3

通过以上工具，我打造了我的新工作环境。

* 思考：

** 我在向 kde 靠拢？
我发现我配置完的 i3wm，和我的 kde 很相似：屏幕最右下方是系统信息（日期，电量，网络，音量等），左下方是工作区列表，窗口名，以及一个开始菜单。我的 kde 界面也是这样的。（ps，这个界面和 windows 一致）。
为什么会这样？我本想通过新的工具，提升工作效率，但是为什么会回到原来的状态？也就是说，原本的 kde 就是我最大工作效率的状态？

回到《跨平台生产力指南--2018 年我对于数字生产力的思考》文章的道的部分，作者提出了 3 个工具要解决的问题： 1.禅模式，2.快速访问 3.通用工具。

在 kde 中如何解决这 3 个问题呢？
1. 禅模式：其实就是将工作区最大化，这个工作区可能是一个 consle，或者 emacs，也可能是 tmux，emacs，或者 firefox+chrome+emacs, 或者是一个 IDEA 等等，只要最大化你当前需要的工具集就行。kde 也可支持平铺模式（[[https://github.com/kwin-scripts/kwin-tiling.git][kwin-tiling]]）。另外，如果你的常用工具本身支持平铺，比如 emacs，tmux，firefox（插件支持），或者工具不需要多窗口，那即使 wm 不支持平铺也没问题。
2. 快速访问：快速访问的意思就是说， 可以在系统顶层直接访问各种资源，包括启动程序，打开文件，打开各种东西的地方。krunner 基本达到了像 rofi，dmenu 这类快速访问工具的一流水准。另外，kde 的开始菜单，是用来打开你不记得名字的工具的，是快速访问功能的一个重要补充。其实，像 krusader，dolphin 等文件浏览工具，也是作为快速访问工具的补充的，核心思想就是，当你不记得名字的时候，可以通过选择的方式，找到你要的资源。
3. 通用工具：在我看来，所谓通用工具包括 2 个问题，1,在不同工具（需要做不同的事情）中共享信息，比如共用终端，共用 emacs，全局剪贴板。 2,用一个工具做不同的事情，比如用 tmux 在一个终端大界面中启动多个命令行工具，在一个 emacs 中编辑多个文件，在 IDEA 中打开多个模块（同一个项目）。好在这些工具在所有环境下都基本可用，都是通用的。 在 kde 下可以用 yakuake，也可以配置 tdop 支持。


** 还有哪里不一样了呢？
还有哪里不一样了呢？不一样的地方有 2 个，一是 i3wm 的窗口平铺特性，二是大量的快捷键。这 2 个问题，在以往的 kde 中并不完整或者我自己没有意识到。

如何解决：

窗口平铺特性：虽然 kde 有 kwin-tiling 支持平铺，但是毕竟不是 kde 原生的，还不完善，比如，和 tdrop 配合不好。解决方法：使用本身支持类平铺功能的软件，比如 tmux，emacs；kde 有 “拼接” 功能，类似 windows 中的拖动窗口到屏幕边缘时，自动将窗口大小改为 1/4 或者 1/2 并放在对应位置。

快捷键：kde 支持自定义快捷键，但是只是简单模式，不支持类似 vi 的模式，也不支持类似 emacs 的键序列。但是，是否真的需要模式或者键序列？在 wm 下绑定快捷键的目的有这些：1. 快速启动程序，2. 操作 wm（切换工作区，移动/缩小/最大化/关闭 某窗口）, 3. 访问通用工具，tdrop，截图，切换输入法，切换大小写等。这些项目并不算多，完全可以依靠一层快捷键搞定。所要做的就是精心定制快捷键。

** 结论：
   回到 kde

需要完成以下事项：
1. 使用 tdrop 快速访问终端，emacs 和 krusade。
2. 使用 krunner
3. 使用 tmux 管理终端，或者仍旧使用 yakuake，但是要合理配置快捷键。
4. 重新定制快捷键

